#!/bin/sh
#
# test-init.sh -- off-device behavioural gate for the procd init script
# (plan 01 / task 5). Runs entirely without procd, ubus, libuci or a router.
#
# It cannot assert the *real* procd instance count or a live reload cold-start
# (that needs a running procd + ubus and is deferred to the task-10 VM run).
# What it CAN prove, by stubbing the procd_* / config_* shell functions the
# script calls and sourcing the real start_service/start_instance/reload/
# service_triggers, is the decision logic this script owns:
#
#   1. start_service runs the config bridge exactly once before opening any
#      instance, and refuses to open ANY instance if the bridge fails
#      (non-zero exit -> no half-configured daemon is ever launched).
#   2. It opens exactly one procd instance per ENABLED section and none for a
#      disabled section (the enabled gate).
#   3. Each opened instance runs the upstream daemon against THAT section's own
#      config.<name>.sh (per-instance, distinct paths -- no collision).
#   4. Each instance exports CAKE_AUTORATE_CONFIG_PREFIX (mandatory: the config
#      dir is not in upstream's default prefix search) and sets respawn.
#   5. An "enabled but not generated by the bridge" section starts nothing
#      (the bridge stays the sole arbiter of enabled).
#   6. reload_service re-runs the bridge and re-declares instances (so procd can
#      cold-start a newly enabled one).
#   7. service_triggers registers the cake-autorate reload trigger.
#
# Exit 0 = all checks passed.

# SC2317: the procd_*/config_* stubs are reached indirectly -- they are called
#         from start_service/start_instance inside the sourced real init script,
#         which shellcheck cannot follow across the `.`-source boundary.
# SC2015: the `cond && ok "..." || fail "..."` idiom is safe here because ok()
#         and fail() both end in printf and always return 0, so the || branch
#         never runs when cond succeeds.
# shellcheck disable=SC2015,SC2317
set -u

here=$(dirname "$0")
root=$(cd "$here/../.." && pwd)
INIT="$root/net/cake-autorate/files/cake-autorate.init"

checks=0
fails=0
ok()   { checks=$((checks + 1)); printf 'ok   %s\n' "$*"; }
fail() { checks=$((checks + 1)); fails=$((fails + 1)); printf 'FAIL %s\n' "$*"; }

# --------------------------------------------------------------------------
# Scenario driver. Runs one start_service (or reload) invocation with a fully
# stubbed procd/uci environment and captures every procd_* call into $CALLS.
#
#   $1 = space-separated "section:enabled" pairs (the simulated UCI)
#   $2 = bridge behaviour: "ok" (generate configs for enabled sections + exit 0),
#        "fail" (exit 1 without generating), or "skip:<name>" (exit 0 but do NOT
#        generate <name>'s config even though it is enabled)
#   $3 = entrypoint to call: "start_service" or "reload_service"
#   $4 = output file to receive the recorded call log
#   $5 = config dir to use (generated stubs land here)
# --------------------------------------------------------------------------
run_scenario() {
	sections="$1"; bridge_mode="$2"; entry="$3"; calls_out="$4"; cfgdir="$5"

	mkdir -p "$cfgdir"

	# --- build the bridge stub -------------------------------------------
	bridge="$cfgdir/.bridge-stub.sh"
	{
		printf '#!/bin/sh\n'
		printf 'echo BRIDGE_CALLED >> "%s"\n' "$calls_out"
		# Record the config-prefix env the init handed us, so a test can prove the
		# init keeps the bridge's output dir in sync with where it reads configs.
		# shellcheck disable=SC2016  # the ${...} must reach the generated stub literally
		printf 'echo "BRIDGE_PREFIX ${CAKE_AUTORATE_CONFIG_PREFIX:-UNSET}" >> "%s"\n' "$calls_out"
		case "$bridge_mode" in
		fail)
			printf 'exit 1\n' ;;
		ok|skip:*)
			skipname=${bridge_mode#skip:}
			[ "$bridge_mode" = "$skipname" ] && skipname=''
			for pair in $sections; do
				name=${pair%%:*}; en=${pair#*:}
				[ "$en" = 1 ] || continue
				[ "$name" = "$skipname" ] && continue
				printf ': > "%s/config.%s.sh"\n' "$cfgdir" "$name"
			done
			printf 'exit 0\n' ;;
		esac
	} > "$bridge"
	chmod +x "$bridge"

	# --- run in an isolated subshell with stubs --------------------------
	: > "$calls_out"
	(
		SECTIONS_SPEC="$sections"
		CALLS="$calls_out"

		# uci stubs
		config_load()     { printf 'LOAD %s\n' "$1" >> "$CALLS"; }
		config_foreach()  { _f="$1"; for _p in $SECTIONS_SPEC; do "$_f" "${_p%%:*}"; done; }
		config_get_bool() {
			# $1 dest var, $2 section, $3 option, $4 default
			_want="$2"; eval "$1=0"
			for _p in $SECTIONS_SPEC; do
				[ "${_p%%:*}" = "$_want" ] && eval "$1=${_p#*:}"
			done
		}

		# procd stubs -- record every call verbatim
		procd_open_instance()      { printf 'OPEN %s\n' "$1" >> "$CALLS"; }
		procd_set_param()          { printf 'PARAM %s\n' "$*" >> "$CALLS"; }
		procd_close_instance()     { printf 'CLOSE\n' >> "$CALLS"; }
		procd_add_reload_trigger() { printf 'TRIGGER %s\n' "$*" >> "$CALLS"; }
		logger()                   { :; }

		# point the script at our fixtures, then load the REAL functions
		export CA_SCRIPT_PREFIX=/fake/scripts
		export CA_CONFIG_PREFIX="$cfgdir"
		export CA_BRIDGE="$bridge"
		# shellcheck disable=SC1090
		. "$INIT"

		"$entry"
		printf 'RC %s\n' "$?" >> "$CALLS"
	)
}

count() { grep -c "$1" "$2" 2>/dev/null || true; }
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM

# ====================================================================== 1,2,3,4
echo "== 1-4. two enabled + one disabled -> two instances, bridge first, per-instance paths"
c="$tmp/calls1"; d="$tmp/cfg1"
run_scenario "wan_dsl:1 wan_lte:1 wan_off:0" ok start_service "$c" "$d"

[ "$(count '^BRIDGE_CALLED$' "$c")" = 1 ] \
	&& ok "bridge invoked exactly once" \
	|| fail "bridge should run exactly once (got $(count '^BRIDGE_CALLED$' "$c"))"

# The init must pass its config prefix to the bridge so generation and lookup
# never desync when CA_CONFIG_PREFIX is non-default.
if grep -qxF "BRIDGE_PREFIX $d" "$c"; then
	ok "init passes CAKE_AUTORATE_CONFIG_PREFIX ($d) to the bridge"
else
	fail "bridge not given the config prefix: $(grep '^BRIDGE_PREFIX' "$c")"
fi

# bridge must precede the first OPEN
first_open=$(grep -n '^OPEN ' "$c" | head -n1 | cut -d: -f1)
first_bridge=$(grep -n '^BRIDGE_CALLED$' "$c" | head -n1 | cut -d: -f1)
if [ -n "$first_open" ] && [ "$first_bridge" -lt "$first_open" ]; then
	ok "bridge runs before any instance is opened"
else
	fail "bridge must run before opening instances (bridge@$first_bridge open@$first_open)"
fi

[ "$(count '^OPEN ' "$c")" = 2 ] \
	&& ok "exactly two instances opened" \
	|| fail "expected 2 instances, got $(count '^OPEN ' "$c")"

grep -q '^OPEN wan_dsl$' "$c" && grep -q '^OPEN wan_lte$' "$c" \
	&& ok "opened wan_dsl and wan_lte (the enabled sections)" \
	|| fail "expected instances wan_dsl and wan_lte"

grep -q '^OPEN wan_off$' "$c" \
	&& fail "disabled section wan_off must NOT be opened" \
	|| ok "disabled section wan_off started nothing"

[ "$(count '^OPEN ' "$c")" = "$(count '^CLOSE$' "$c")" ] \
	&& ok "every opened instance is closed (balanced open/close)" \
	|| fail "unbalanced open/close: $(count '^OPEN ' "$c") open vs $(count '^CLOSE$' "$c") close"

grep -q '^PARAM command /fake/scripts/cake-autorate.sh '"$d"'/config.wan_dsl.sh$' "$c" \
	&& grep -q '^PARAM command /fake/scripts/cake-autorate.sh '"$d"'/config.wan_lte.sh$' "$c" \
	&& ok "each daemon points at its own config.<name>.sh (distinct per-instance paths)" \
	|| fail "per-instance command/config path wiring is wrong"

[ "$(count '^PARAM env CAKE_AUTORATE_CONFIG_PREFIX='"$d"'$' "$c")" = 2 ] \
	&& ok "both instances export CAKE_AUTORATE_CONFIG_PREFIX" \
	|| fail "CAKE_AUTORATE_CONFIG_PREFIX not exported for every instance"

[ "$(count '^PARAM respawn' "$c")" = 2 ] \
	&& ok "both instances set respawn (procd supervises each)" \
	|| fail "respawn not set on every instance"

grep -q '^RC 0$' "$c" \
	&& ok "start_service returned 0 on success" \
	|| fail "start_service should return 0 on success"

# ====================================================================== 1 (abort)
echo
echo "== 5. bridge failure aborts: no instance is opened, non-zero return"
c="$tmp/calls2"; d="$tmp/cfg2"
run_scenario "wan_dsl:1 wan_lte:1" fail start_service "$c" "$d"

[ "$(count '^OPEN ' "$c")" = 0 ] \
	&& ok "no instance opened when the bridge fails" \
	|| fail "instances were opened despite bridge failure ($(count '^OPEN ' "$c"))"

grep -q '^RC 0$' "$c" \
	&& fail "start_service must NOT return 0 when the bridge fails" \
	|| ok "start_service returned non-zero on bridge failure"

# ====================================================================== 5 (skip)
echo
echo "== 6. enabled but bridge generated no config -> that instance starts nothing"
c="$tmp/calls3"; d="$tmp/cfg3"
run_scenario "wan_dsl:1 wan_lte:1" skip:wan_lte start_service "$c" "$d"

grep -q '^OPEN wan_dsl$' "$c" \
	&& ok "wan_dsl (config generated) is opened" \
	|| fail "wan_dsl should be opened"

grep -q '^OPEN wan_lte$' "$c" \
	&& fail "wan_lte has no generated config and must not be opened" \
	|| ok "wan_lte (no generated config) started nothing -- bridge stays the arbiter"

# ====================================================================== reload
echo
echo "== 7. reload_service re-runs the bridge and re-declares instances (cold-start path)"
c="$tmp/calls4"; d="$tmp/cfg4"
run_scenario "wan_dsl:1 wan_lte:1 wan_new:1" ok reload_service "$c" "$d"

[ "$(count '^BRIDGE_CALLED$' "$c")" = 1 ] \
	&& ok "reload re-runs the bridge" \
	|| fail "reload should re-run the bridge"

[ "$(count '^OPEN ' "$c")" = 3 ] \
	&& ok "reload re-declares all enabled instances incl. a newly enabled one" \
	|| fail "reload should declare 3 instances, got $(count '^OPEN ' "$c")"

# ====================================================================== triggers
echo
echo "== 8. service_triggers registers the cake-autorate reload trigger"
c="$tmp/calls5"
(
	CALLS="$c"; : > "$CALLS"
	procd_add_reload_trigger() { printf 'TRIGGER %s\n' "$*" >> "$CALLS"; }
	# shellcheck disable=SC1090
	. "$INIT"
	service_triggers
)
grep -q '^TRIGGER cake-autorate$' "$c" \
	&& ok "procd_add_reload_trigger cake-autorate registered" \
	|| fail "service_triggers must register the cake-autorate reload trigger"

# --------------------------------------------------------------------------
echo
if [ "$fails" -eq 0 ]; then
	printf 'PASS: %d checks\n' "$checks"
	exit 0
else
	printf 'FAIL: %d/%d checks failed\n' "$fails" "$checks"
	exit 1
fi
