'use strict';
'require view';
'require form';
'require ui';
'require rpc';
'require cake-autorate.options as options';
'require cake-autorate.live as live';

/*
 * cake-autorate configuration form.
 *
 * A form.Map over the `cake-autorate` UCI type with a named, add/removable
 * TypedSection, so multiple instances can be created, edited, enabled and
 * deleted. Fields are grouped into tabs led by Essentials, with a search box
 * that filters across every group. Every field except the package-local
 * `enabled` procd gate is generated by iterating options.OPTIONS -- the 66
 * upstream options -- so the form cannot drift from what the daemon accepts.
 *
 * Live status lives in a separate view (view/cake-autorate/status.js). This
 * file is config editing plus the SQM-validated dl_if / ul_if pickers: both are
 * comboboxes filled from the `sqm_interfaces` rpcd method, and both show a
 * warning (never a block) when the chosen interface has no live SQM CAKE qdisc
 * behind it. The version shown is the PACKAGE version 3.2.2, not the 3.2.1 the
 * daemon reports for itself -- upstream forgot to bump that at tag v3.2.2.
 *
 * Selectors the Playwright suites rely on:
 *   - each option row:      div.cbi-value[data-name="<uci_option>"]
 *   - the interface warn:   div.cbi-value[data-name="dl_if"|"ul_if"]
 *                            .cake-if-warn[data-level="ok|warn|info"]
 *   - the section:          UCI type "cake-autorate", named (anonymous=false)
 *   - the search box:       input#cake-autorate-filter
 *   - the group tabs:       [data-tab="essentials|shaper|pingers|reflectors|
 *                            detection|idle|logging"]
 */

var PKG_VERSION = '3.2.2';
/* The upstream REPOSITORY, not its wiki -- the wiki has no pages and
 * 302-redirects here anyway, so linking it just sent readers through a bounce.
 * Named for what it points at, since "upstream" tells a reader nothing about
 * where they are about to land. */
var DOC_URL = 'https://github.com/lynxthecat/cake-autorate';
var DOC_TITLE = _('lynxthecat/cake-autorate documentation');

/* Derives the shaping interfaces from the live SQM config, so dl_if / ul_if can
 * offer checked choices instead of free text. */
var callSqmInterfaces = rpc.declare({
	object: 'cake-autorate',
	method: 'sqm_interfaces',
	expect: { '': {} }
});

var TABS = [
	{ id: 'essentials', title: _('Essentials'),
	  descr: _('Required configuration to use cake-autorate. You must set all of these options, even if upload or download shaping is disabled.') },
	{ id: 'shaper', title: _('Shaper rates & response'),
	  descr: _('How aggressively the shaper rate is moved up and down in response to load and bufferbloat.'), doc: true },
	{ id: 'pingers', title: _('Pingers'),
	  descr: _('Which probe binary is used and how many reflectors are pinged how often.') },
	{ id: 'reflectors', title: _('Reflectors'),
	  descr: _('The pool of ICMP targets and how misbehaving ones are detected and rotated out.'), doc: true },
	{ id: 'detection', title: _('Delay & bufferbloat detection'),
	  descr: _('One-way-delay thresholds and the EWMA smoothing that decide when the link is bufferbloated.'), doc: true },
	{ id: 'idle', title: _('Idle, sleep & stalls'),
	  descr: _('When the connection counts as idle or stalled and how the pingers sleep to save CPU.') },
	{ id: 'logging', title: _('Logging & output'),
	  descr: _('Which log streams the daemon emits. Options marked package-managed are overridden by the service so the status view and collectd always have data.') }
];

/*
 * How one underscore-separated word of a UCI option name is rendered in the
 * field title.
 *
 * Two rules, and they pull in opposite directions on purpose. A genuine
 * acronym (OWD, EWMA, CAKE) is written the way its field is discussed
 * everywhere else, in capitals. Everything else is a TRUNCATION -- min, max,
 * thr, avg, args, if, no -- and truncations are expanded, because a form is
 * read by someone who does not yet know the vocabulary and "Min" is only
 * shorter for the person who already did.
 *
 * `dl`/`ul` sit in the second group despite looking like the first: nothing
 * else in this UI says DL, the status table's own columns are headed Download
 * and Upload, and the two differ by one letter in a form that lists both.
 *
 * A mapped word is emitted VERBATIM (only unmapped words get capitalised by
 * humanize), so every value here carries its own casing.
 */
var ACRONYMS = {
	/* acronyms -- kept, in their own casing */
	owd: 'OWD', ewma: 'EWMA', cake: 'CAKE',
	/* truncations -- expanded */
	dl: 'Download', ul: 'Upload', min: 'Minimum', max: 'Maximum',
	thr: 'Threshold', avg: 'Average', 'no': 'Number of', 'if': 'Interface',
	args: 'Arguments',
	/* units */
	kbps: 'Kbit/s', ms: 'ms', kb: 'KB', mins: 'min'
};

function humanize(name) {
	return name.split('_').map(function (w) {
		return ACRONYMS[w.toLowerCase()] || (w.charAt(0).toUpperCase() + w.slice(1));
	}).join(' ');
}

/*
 * The visible help for one option: prose plus its unit/range hint.
 *
 * Deliberately does not print the UCI key. No LuCI app in the feed does, not
 * even luci-app-sqm -- the closest comparison, which also wraps a documented
 * shaper and still writes "Latency target (ingress)" rather than `itarget`.
 * Repeating the key on all 66 rows is noise, and it stays reachable anyway: the
 * search box matches UCI names, and every row carries data-name in the DOM.
 */
function describe(opt) {
	var d = opt.desc;
	if (opt.units)
		d += '  —  ' + opt.units;
	return d;
}

/*
 * Turn a checkRateOrder() code into a sentence that names the two fields in the
 * words the form uses, states the rule, and shows the values that broke it.
 */
function rateOrderMessage(dir, err) {
	var d = (dir === 'dl') ? _('download') : _('upload');
	switch (err.code) {
		case 'min-gt-base':
			return _('Minimum %s rate (%d) must not exceed the base rate (%d).').format(d, err.a, err.b);
		case 'max-lt-base':
			return _('Maximum %s rate (%d) must not be below the base rate (%d).').format(d, err.a, err.b);
		default:
			return _('Minimum %s rate (%d) must not exceed the maximum rate (%d).').format(d, err.a, err.b);
	}
}

/* A tab description node with an optional upstream documentation link. */
function tabDescr(tab) {
	if (!tab.doc)
		return tab.descr;
	return E('span', {}, [
		tab.descr, ' ',
		E('a', { 'href': DOC_URL, 'target': '_blank', 'rel': 'noreferrer' }, DOC_TITLE + ' →')
	]);
}

/* --- search/filter -------------------------------------------------------
 * Shows every tab pane at once (via the .cake-filtering class and the injected
 * CSS) and hides option rows whose UCI name or title does not match. Clearing
 * the box restores normal tab behaviour. The matching itself lives in
 * options.optionMatches, which is pure and unit-tested. */
function applyFilter(mapEl, statusEl, query) {
	var q = String(query || '').trim();
	var rows = mapEl.querySelectorAll('.cbi-value[data-name]');
	var shown = 0;

	if (q === '') {
		mapEl.classList.remove('cake-filtering');
		rows.forEach(function (r) { r.style.removeProperty('display'); });
		statusEl.textContent = '';
		return;
	}

	mapEl.classList.add('cake-filtering');
	rows.forEach(function (r) {
		var name = r.getAttribute('data-name') || '';
		var titleEl = r.querySelector('.cbi-value-title');
		var title = titleEl ? titleEl.textContent : '';
		if (options.optionMatches(q, name, title)) {
			r.style.removeProperty('display');
			shown++;
		}
		else {
			r.style.display = 'none';
		}
	});

	statusEl.textContent = (shown === 0)
		? _('No options match "%s"').format(q)
		: _('%d option field(s) match "%s"').format(shown, q);
}

/* CSS class for a dl_if/ul_if warning level. */
function warnClass(level) {
	if (level === 'warn') return 'alert-message warning';
	if (level === 'info') return 'alert-message';
	if (level === 'ok') return 'cake-if-ok';
	return '';
}

/*
 * Refresh the SQM notice under one section's dl_if/ul_if widget. The value is
 * never rejected, only annotated, so an existing value still shows even when
 * SQM is not configured. The decision itself (live.interfaceStatus) is pure and
 * unit-tested.
 */
function updateIfWarning(opt, section_id, direction, sqm) {
	var el = opt.getUIElement(section_id);
	if (!el || !el.node)
		return;
	var field = el.node.parentNode;
	if (!field)
		return;

	var res = live.interfaceStatus(el.getValue(), sqm, direction);
	var node = field.querySelector('.cake-if-warn');

	if (res.level === 'none') {
		if (node)
			node.remove();
		return;
	}

	if (!node) {
		node = E('div', { 'class': 'cake-if-warn' });
		field.appendChild(node);
	}
	node.className = 'cake-if-warn ' + warnClass(res.level);
	node.setAttribute('data-level', res.level);
	node.setAttribute('data-direction', direction);
	node.textContent = res.message;
}

return view.extend({
	render: function () {
		return callSqmInterfaces().then(L.bind(this.renderForm, this), L.bind(function () {
			/* rpcd unreachable (e.g. package not yet installed): fall back to an
			 * empty, not-present SQM view -- fields stay usable, warnings say so. */
			return this.renderForm({});
		}, this));
	},

	renderForm: function (sqm) {
		var ifChoices = live.interfaceChoices(sqm);

		/* The form must render exactly the 66 upstream options, split across
		 * groups as expected. If it does not, say so rather than let the page
		 * look complete -- that catches both a UI option the daemon has never
		 * heard of and an option quietly dropped from the list. */
		var coverage = options.coverageReport(options.OPTIONS);

		var m = new form.Map('cake-autorate', _('CAKE Autorate'),
			_('Adaptive per-flow bandwidth control for CAKE SQM. Each section below is one independent instance (one WAN). The section name is the instance id and names the daemon config, log file and service.'));

		var s = m.section(form.TypedSection, 'cake-autorate');
		s.anonymous = false;
		s.addremove = true;
		s.addbtntitle = _('Add instance');

		/*
		 * "Add instance" stays a TEXT field with suggestions rather than becoming a
		 * dropdown, for three reasons:
		 *   1. The id must be a UCI section name ([a-zA-Z0-9_]+), but real WAN
		 *      devices are routinely pppoe-wan / eth0.2 / wan.835 -- a dropdown of
		 *      live interfaces would offer names UCI then rejects.
		 *   2. The id is a free-form label naming the daemon config, log file and
		 *      service; a closed list would block legitimate names (starlink,
		 *      backup_lte) and there is no 1:1 interface->instance mapping anyway,
		 *      since an instance carries dl_if AND ul_if as options.
		 *   3. It matches the feed: the apps that override renderSectionAdd
		 *      (mwan3, libreswan, strongswan-swanctl, xfrpc) all AUGMENT the name
		 *      input with validators; none swap it for a select.
		 * So: native <datalist> suggestions derived from the SQM egress devices,
		 * plus a validator that explains the naming rule and catches duplicates.
		 */
		s.renderSectionAdd = function (extra_class) {
			var el = form.TypedSection.prototype.renderSectionAdd.apply(this, arguments);
			var nameEl = el.querySelector('.cbi-section-create-name');
			if (!nameEl)
				return el;

			var suggestions = options.instanceNameSuggestions(ifChoices.ul, this.cfgsections());
			if (suggestions.length) {
				var listId = 'cake-autorate-instance-names';
				el.appendChild(E('datalist', { 'id': listId },
					suggestions.map(function (n) { return E('option', { 'value': n }); })));
				nameEl.setAttribute('list', listId);
				nameEl.setAttribute('placeholder', _('e.g. %s').format(suggestions[0]));
			}
			else {
				nameEl.setAttribute('placeholder', _('e.g. wan'));
			}

			/*
			 * A second validator on the same input. ui.addValidator adds a
			 * listener rather than replacing one, so the built-in validator keeps
			 * enabling the Add button and enforcing the uciname character set,
			 * and this one adds the check it cannot make: a name already in use.
			 * Bad characters are left to 'uciname' -- its assert runs before this
			 * callback, so a message here would never be seen, and users get
			 * LuCI's standard wording as they do everywhere else. Marking the
			 * field invalid is enough to block creation: the Add handler bails on
			 * a field carrying .cbi-input-invalid.
			 */
			var section = this;
			ui.addValidator(nameEl, 'uciname', true, function (v) {
				if (v !== '' && section.cfgsections().indexOf(v) !== -1)
					return _('An instance named "%s" already exists.').format(v);
				return true;
			}, 'blur', 'keyup');

			return el;
		};

		TABS.forEach(function (t) {
			s.tab(t.id, t.title, tabDescr(t));
		});

		/* The procd gate. Not one of the 66 upstream options and never written
		 * into the daemon config; leads the Essentials tab. */
		var en = s.taboption('essentials', form.Flag, 'enabled', _('Enabled'),
			_('Master switch for this instance (procd). Turn on once the interfaces and rates are correct for your line.'));
		en.rmempty = false;

		/* dl_if / ul_if options, captured so the post-render pass can seed their
		 * warnings for every existing section. */
		var ifOpts = {};
		/* Every generated option, so the shaper-rate trios can be wired up after
		 * the loop (a trio needs all three members to exist first). */
		var rateOpts = {};

		/* One field per upstream option, generated from the metadata, so the
		 * form always matches options.OPTIONS. */
		options.OPTIONS.forEach(function (opt) {
			var o, dt = options.datatypeFor(opt);
			var title = humanize(opt.name);
			var descr = describe(opt);

			/* The two interface fields become comboboxes offering the SQM-derived
			 * devices. Free text is still accepted, so a value set before SQM
			 * existed keeps showing; a value SQM does not back raises a warning
			 * rather than blocking the save. */
			if (opt.name === 'dl_if' || opt.name === 'ul_if') {
				var direction = (opt.name === 'dl_if') ? 'dl' : 'ul';
				var choices = (direction === 'dl') ? ifChoices.dl : ifChoices.ul;
				o = s.taboption(opt.group, form.Value, opt.name, title, descr);
				choices.forEach(function (c) { o.value(c, c); });
				o.rmempty = true;
				o.onchange = function (ev, section_id) {
					updateIfWarning(this, section_id, direction, sqm);
				};
				ifOpts[opt.name] = { opt: o, direction: direction };
				return;
			}

			if (opt.type === 'bool') {
				o = s.taboption(opt.group, form.Flag, opt.name, title, descr);
			}
			else if (opt.type === 'list') {
				o = s.taboption(opt.group, form.DynamicList, opt.name, title, descr);
				o.datatype = 'ipaddr';
			}
			else if (opt.type === 'string' && opt.choices) {
				o = s.taboption(opt.group, form.ListValue, opt.name, title, descr);
				opt.choices.forEach(function (c) { o.value(c, c); });
			}
			else {
				o = s.taboption(opt.group, form.Value, opt.name, title, descr);
				if (dt)
					o.datatype = dt;
			}

			/* String options whose upstream default is empty may be blanked;
			 * everything else keeps its packaged/upstream default when omitted. */
			o.rmempty = true;
			rateOpts[opt.name] = o;
		});

		/* Enforce the min <= base <= max ordering the Essentials help promises.
		 * A datatype only sees its own field, so without this the form happily
		 * saved min > base and handed the daemon a nonsensical config. Attached
		 * to all six fields so the error appears on whichever one the user is
		 * editing; returning a string makes LuCI show it under the field and
		 * refuse the save. */
		options.RATE_TRIOS.forEach(function (trio) {
			var members = [trio.min, trio.base, trio.max];

			members.forEach(function (name) {
				var o = rateOpts[name];
				if (!o)
					return;

				o.validate = function (section_id, value) {
					var self = this;
					function other(n) {
						/* Take the field being edited from `value`; read the
						 * other two off their widgets. */
						if (n === name)
							return value;
						var found = self.map.lookupOption(n, section_id);
						return (found && found[0]) ? found[0].formvalue(section_id) : null;
					}
					var err = options.checkRateOrder(other(trio.min), other(trio.base), other(trio.max));
					return err ? rateOrderMessage(trio.dir, err) : true;
				};

				/* Re-validate the siblings too: fixing `base` must clear a stale
				 * error still shown on `min`, which only re-checks itself. */
				o.onchange = function (ev, section_id) {
					members.forEach(function (n) {
						if (n === name)
							return;
						var found = this.map.lookupOption(n, section_id);
						if (found && found[0])
							found[0].triggerValidation(section_id);
					}, this);
				};
			});
		});

		return m.render().then(function (mapEl) {
			var nodes = [];

			/* CSS: while filtering, reveal every tab pane and hide the tab bar
			 * so cross-group matches are visible. */
			nodes.push(E('style', { 'type': 'text/css' },
				'.cake-filtering [data-tab-title]{height:auto !important;opacity:1 !important;overflow:visible !important;}' +
				'.cake-filtering .cbi-tabmenu{display:none !important;}' +
				'.cake-filtering .cbi-tab-descr{display:none !important;}' +
				'#cake-autorate-toolbar{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;margin:.5em 0;}' +
				'#cake-autorate-filter{flex:1 1 20em;max-width:32em;}' +
				'#cake-autorate-filter-status{opacity:.75;font-size:90%;}' +
				'.cake-if-warn{margin-top:.4em;padding:.4em .6em;font-size:90%;}' +
				'.cake-if-warn.cake-if-ok{color:#2e7d32;padding:.2em 0;}'));

			nodes.push(E('p', {}, [
				E('strong', {}, 'cake-autorate ' + PKG_VERSION), ' · ',
				E('a', { 'href': DOC_URL, 'target': '_blank', 'rel': 'noreferrer' }, DOC_TITLE)
			]));

			/* The one thing this page cannot say field by field: SQM is missing
			 * altogether, so there is no qdisc for any instance to adjust.
			 *
			 * Its counterpart -- naming the egress/ingress choices when SQM IS
			 * configured -- used to sit here too and is gone: the interface
			 * fields already offer exactly those devices in their dropdowns and
			 * annotate the chosen one underneath, so restating the same two
			 * lists at the top of the page was a third copy of an answer the
			 * user is looking straight at. */
			if (!(sqm && sqm.sqm_config_present)) {
				nodes.push(E('p', { 'id': 'cake-autorate-sqm-note', 'class': 'cbi-value-description' },
					_('SQM is not configured yet, so the interface fields cannot be validated against a live CAKE qdisc. Configure SQM first; the fields still accept a value.')));
			}

			if (!coverage.ok) {
				nodes.push(E('div', { 'class': 'alert-message error' }, [
					E('strong', {}, _('Configuration form coverage check FAILED.')), ' ',
					_('The form no longer renders exactly the 66 supported options: %s')
						.format(coverage.errors.join('; '))
				]));
			}

			/* Search / filter toolbar. */
			var statusEl = E('span', { 'id': 'cake-autorate-filter-status' }, '');
			var inputEl = E('input', {
				'id': 'cake-autorate-filter',
				'type': 'search',
				'class': 'cbi-input-text',
				/* Mentions UCI names on purpose: with the keys no longer printed
				 * on each row, this is how someone reading the upstream docs
				 * finds the field for a config key. */
				'placeholder': _('Search titles and UCI option names, e.g. "shaper" or "owd_delta"…'),
				'autocomplete': 'off',
				'keyup': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); },
				'search': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); }
			});
			nodes.push(E('div', { 'id': 'cake-autorate-toolbar' }, [
				E('label', { 'for': 'cake-autorate-filter' }, _('Search options') + ':'),
				inputEl, statusEl
			]));

			nodes.push(mapEl);

			/* Seed the dl_if/ul_if warnings for every existing section (onchange
			 * only fires on edit). getUIElement no-ops safely if a widget is not
			 * yet in the DOM. */
			var sids = s.cfgsections();
			Object.keys(ifOpts).forEach(function (name) {
				var entry = ifOpts[name];
				sids.forEach(function (sid) {
					updateIfWarning(entry.opt, sid, entry.direction, sqm);
				});
			});

			return E('div', {}, nodes);
		});
	}
});
