'use strict';
'require view';
'require form';
'require ui';
'require rpc';
'require cake-autorate.options as options';
'require cake-autorate.live as live';

/*
 * cake-autorate configuration form.
 *
 * A form.Map over the `cake-autorate` UCI type with a named, add/removable
 * TypedSection, so multiple instances can be created, edited, enabled and
 * deleted. Fields are grouped into tabs led by Essentials, with a search box
 * that filters across every group. Every field except the package-local
 * `enabled` procd gate is generated by iterating options.OPTIONS -- the 66
 * upstream options -- so the form cannot drift from what the daemon accepts.
 *
 * Live status lives in a separate view (view/cake-autorate/status.js). This
 * file is config editing plus the SQM-validated dl_if / ul_if pickers: both are
 * comboboxes filled from the `sqm_interfaces` rpcd method, and both show a
 * warning (never a block) when the chosen interface has no live SQM CAKE qdisc
 * behind it. The version in the footer is the PACKAGE version -- the upstream
 * tag net/cake-autorate/Makefile pins -- and NOT the version the daemon reports
 * for itself, which upstream forgot to bump and which therefore trails it.
 *
 * Selectors the Playwright suites rely on:
 *   - each option row:      div.cbi-value[data-name="<uci_option>"]
 *   - the interface warn:   div.cbi-value[data-name="dl_if"|"ul_if"]
 *                            .cake-if-warn[data-level="ok|warn|info"]
 *   - the section:          UCI type "cake-autorate", named (anonymous=false)
 *   - the search box:       input#cake-autorate-filter
 *   - the group tabs:       [data-tab="essentials|shaper|pingers|reflectors|
 *                            detection|idle|logging"]
 */

/*
 * The upstream tag this feed builds, restated for the footer and used to pin
 * the per-option reference link below.
 *
 * RENOVATE OWNS THIS LINE. The `lynxthecat/cake-autorate` custom manager in
 * renovate.json rewrites it in the same PR that moves PKG_VERSION in
 * net/cake-autorate/Makefile, and tests/regression/test-upstream-version-pin.sh
 * fails if the two ever disagree. It was NOT covered by that manager until the
 * manager was widened, so the next automatic bump would have left this page
 * naming a version the feed does not build.
 *
 * Do not hand-edit it, and do not restate the version anywhere else in this
 * file -- a second literal is a second thing to get wrong, and only this one is
 * rewritten. The pin test fails on a stray copy for that reason.
 *
 * Named UPSTREAM_VERSION, not PKG_VERSION: this package has a PKG_VERSION of
 * its own (luci-app-cake-autorate follows the repo tag) and it is not this one.
 */
var UPSTREAM_VERSION = '3.2.2';

/*
 * Upstream's per-option reference, which is defaults.sh and not the README.
 *
 * The README documents the PROJECT -- theory of operation, installation -- and
 * names individual options only in passing prose, under no heading of their
 * own. There is no anchor to link an option to, so a per-option deep link into
 * it is not a thing that exists. defaults.sh is where every option is actually
 * written down, one per line, each with its own comment.
 *
 * That makes this a deep link in practice without being one in the URL: each
 * row of the form now prints its UCI key (see describe()), and the key is what
 * the reader searches for once they land here. Doing it as 66 real
 * "blob/<tag>/defaults.sh#L<n>" links was the alternative and was rejected --
 * that is 66 line numbers to re-check by hand on every upstream bump, silently
 * wrong the moment upstream inserts a line, to save one Ctrl-F.
 *
 * Pinned to the tag we actually ship rather than to a branch, so the file a
 * reader lands on is the one their daemon was built from: upstream keeps
 * adding and renaming options, and HEAD would document some this package does
 * not have.
 *
 * It concatenates UPSTREAM_VERSION rather than spelling the number a second
 * time: that is the single-literal rule above, and it is also why this link
 * needs no attention on a bump. Renovate moves the constant and the URL follows.
 */
var DOC_URL = 'https://github.com/lynxthecat/cake-autorate/blob/v' +
	UPSTREAM_VERSION + '/defaults.sh';
var DOC_TITLE = _('Upstream option reference (defaults.sh)');

/* Derives the shaping interfaces from the live SQM config, so dl_if / ul_if can
 * offer checked choices instead of free text. */
var callSqmInterfaces = rpc.declare({
	object: 'cake-autorate',
	method: 'sqm_interfaces',
	expect: { '': {} }
});

var TABS = [
	{ id: 'essentials', title: _('Essentials'),
	  descr: _('Required configuration to use cake-autorate. You must set all of these options, even if upload or download shaping is disabled.') },
	{ id: 'shaper', title: _('Shaper rates & response'),
	  descr: _('How aggressively the shaper rate is moved up and down in response to load and bufferbloat.') },
	{ id: 'pingers', title: _('Pingers'),
	  descr: _('Which probe binary is used and how many reflectors are pinged how often.') },
	{ id: 'reflectors', title: _('Reflectors'),
	  descr: _('The pool of ICMP targets and how misbehaving ones are detected and rotated out.') },
	{ id: 'detection', title: _('Delay & bufferbloat detection'),
	  descr: _('One-way-delay thresholds and the EWMA smoothing that decide when the link is bufferbloated.') },
	{ id: 'idle', title: _('Idle, sleep & stalls'),
	  descr: _('When the connection counts as idle or stalled and how the pingers sleep to save CPU.') },
	{ id: 'logging', title: _('Logging & output'),
	  descr: _('Which log streams the daemon emits. Options marked package-managed are overridden by the service so the status view and collectd always have data.') }
];

/*
 * How one underscore-separated word of a UCI option name is rendered in the
 * field title.
 *
 * Two rules, and they pull in opposite directions on purpose. A genuine
 * acronym (OWD, EWMA, CAKE) is written the way its field is discussed
 * everywhere else, in capitals. Everything else is a TRUNCATION -- min, max,
 * thr, avg, args, if, no -- and truncations are expanded, because a form is
 * read by someone who does not yet know the vocabulary and "Min" is only
 * shorter for the person who already did.
 *
 * `dl`/`ul` sit in the second group despite looking like the first: nothing
 * else in this UI says DL, the status table's own columns are headed Download
 * and Upload, and the two differ by one letter in a form that lists both.
 *
 * A mapped word is emitted VERBATIM (only unmapped words get capitalised by
 * humanize), so every value here carries its own casing.
 */
var ACRONYMS = {
	/* acronyms -- kept, in their own casing */
	owd: 'OWD', ewma: 'EWMA', cake: 'CAKE',
	/* truncations -- expanded */
	dl: 'Download', ul: 'Upload', min: 'Minimum', max: 'Maximum',
	thr: 'Threshold', avg: 'Average', 'no': 'Number of', 'if': 'Interface',
	args: 'Arguments'
};

/*
 * Trailing unit suffixes, rendered as a parenthesised unit rather than as
 * another word of the title: "Startup Wait (seconds)", not "Startup Wait S".
 *
 * They are spelled out for the same reason the truncations above are, with one
 * exception -- Kbit/s, which is how a rate is written on every ISP's own page
 * and in luci-app-sqm next door, and whose expansion ("kilobits per second")
 * nobody wants in a field label.
 *
 * Applied ONLY to the last word of a name. Every one of these is a suffix in
 * the 66 upstream keys, and a `_s_` in the middle of some future name would be
 * a word, not a unit.
 */
var UNITS = {
	kbps: 'Kbit/s', ms: 'milliseconds', s: 'seconds', mins: 'minutes',
	kb: 'kilobytes', b: 'bytes'
};

/*
 * Titles humanize() must not be allowed to derive from the key.
 *
 * humanize() splits on "_" and cannot know that up|load and down|load are a
 * boundary between two ideas rather than a split word, so
 * shaper_rate_adjust_up_load_high came out as "Shaper Rate Adjust Up Load
 * High" -- which reads as UPLOAD, the one thing it does not mean.
 *
 * "Up"/"down" is the direction of the rate MULTIPLIER; "load high"/"load low"
 * is the traffic-load condition that triggers it. Upstream defaults.sh says so
 * in its own comments -- 1.04 is "how rapidly to increase shaper rate upon high
 * load detected", 0.99 and 1.01 are "how rapidly to return down/up to base
 * shaper rate upon idle or low load detected" -- and the defaults confirm it:
 * the "up" keys are >= 1 and the "down" key is <= 1. Traffic direction is
 * dl/ul everywhere in this config (adjust_dl_shaper_rate, min_ul_shaper_rate_
 * kbps) and never up/down, so there is no reading where these three name one.
 *
 * These are the only three keys where the generic path lands on a wrong word,
 * so this stays a short exception list rather than a second naming scheme.
 */
var TITLE_OVERRIDES = {
	shaper_rate_adjust_up_load_high: _('Rate Increase While Load Is High'),
	shaper_rate_adjust_down_load_low: _('Decay Toward Base From Above (low load)'),
	shaper_rate_adjust_up_load_low: _('Decay Toward Base From Below (low load)')
};

function humanize(name) {
	if (TITLE_OVERRIDES[name])
		return TITLE_OVERRIDES[name];

	var words = name.split('_');
	var unit = (words.length > 1) ? UNITS[words[words.length - 1].toLowerCase()] : null;
	if (unit)
		words = words.slice(0, -1);

	var title = words.map(function (w) {
		return ACRONYMS[w.toLowerCase()] || (w.charAt(0).toUpperCase() + w.slice(1));
	}).join(' ');

	return unit ? (title + ' (' + unit + ')') : title;
}

/*
 * SUBHEADINGS -- an option name that a heading is drawn immediately BEFORE.
 *
 * Essentials lists six rate fields whose titles differ only by the direction
 * word buried in the middle of each: Minimum Download Shaper Rate, then five
 * more of the same shape. Read at a glance they are one undifferentiated block
 * of six, and the field you want is found by reading every title. Two headings
 * split it into the two trios it always was, so the direction is established
 * once, above the group, instead of once per row.
 */
var SUBHEADINGS = {
	min_dl_shaper_rate_kbps: _('Download rates'),
	min_ul_shaper_rate_kbps: _('Upload rates')
};

/*
 * A full-width heading occupying one option row.
 *
 * form.DummyValue is the base because it already declines to touch UCI --
 * write() and remove() are no-ops upstream -- so a heading can never reach the
 * config bridge as a stray key. cfgvalue() is stubbed for the same reason: with
 * no UCI option behind the name there is nothing to read either.
 *
 * The title is left EMPTY on purpose. form.js only builds the label column and
 * the value column when a title is set, so an empty one gives the heading the
 * whole row instead of indenting it into the value column like a field value.
 */
var SubHeading = form.DummyValue.extend({
	__name__: 'CBI.CakeSubHeading',

	cfgvalue: function () { return null; },

	/*
	 * Nothing to parse, and saying so matters. The inherited parse() treats a
	 * rendered row with no widget value as an EMPTY REQUIRED field and rejects
	 * the whole Save & Apply with 'Option "..." must not be empty' -- a heading
	 * has no value by construction, so it would block every save on the page.
	 */
	parse: function () { return Promise.resolve(); },

	renderWidget: function () {
		return E('h4', { 'class': 'cake-subhead' }, this.subhead);
	}
});

/*
 * The visible help for one option: the sentence, then the UCI key it writes.
 *
 * The sentence is opt.desc verbatim -- whole sentences that carry their own
 * units and constraints. It used to be desc plus a separate hint glued on after
 * an em dash -- "Rotate the log file once this many KB of log lines have
 * accumulated.  —  KB, > 0" -- which said the unit twice, in two registers,
 * and made the sentence the shorter half of its own help text.
 *
 * WHY THE KEY IS PRINTED AFTER ALL
 *   This used to end at the sentence, on the grounds that no LuCI app in the
 *   feed prints UCI keys (luci-app-sqm writes "Latency target (ingress)", not
 *   `itarget`), that 66 repeats are noise, and that the key stays reachable via
 *   the search box and each row's data-name.
 *
 *   That reasoning answers "how do I find this FIELD", which the search box
 *   does solve. It does not answer "what does upstream say about this option",
 *   which is the question the key actually gets asked for: upstream documents
 *   every option by its key in defaults.sh, this form paraphrases them into
 *   prose, and TITLE_OVERRIDES above now deliberately breaks the last
 *   mechanical link between title and key. Without the key on the row there is
 *   nothing to carry across to upstream's file, a `grep`, or a forum thread --
 *   and data-name is only reachable by opening devtools.
 *
 * WHY IT IS MARKUP AND NOT A NODE
 *   form.js renders the description ONLY when typeof description === 'string'
 *   (a Node or an array is silently dropped and the help vanishes), and
 *   luci.js dom.append assigns a bare string child through innerHTML. So <code>
 *   here is rendered as an element, and escaping is this function's problem.
 *   Every name is a hardcoded literal in options.js -- never user input, never
 *   a UCI value -- and no desc string contains <, > or &, so there is nothing
 *   to escape. opt.doc is interpolated into an href on the same terms, and is
 *   likewise a literal. All three are asserted by the unit test.
 */
function describe(opt) {
	var help = opt.desc + ' (<code>' + opt.name + '</code>)';

	/* The eight algorithm options carry opt.doc (see options.js DOC). Separator
	 * is the middot this page already uses between the version and the header
	 * link, NOT an em dash: an earlier pass took em-dash tails out of this help
	 * text because what followed them restated the sentence in a worse register.
	 * A link is not that -- it is somewhere else to go, and it only appears on
	 * the rows where a sentence provably is not enough. */
	if (opt.doc)
		help += ' \u00b7 <a href="' + opt.doc + '" target="_blank"' +
			' rel="noreferrer">' + _('Theory of Operation') + '</a>';

	return help;
}

/*
 * Turn a checkRateOrder() code into a sentence that names the two fields in the
 * words the form uses, states the rule, and shows the values that broke it.
 *
 * BOTH fields are named in full, direction included. "must not exceed the base
 * rate" leaves the reader to work out which base -- and this form has two of
 * every rate, so an error raised on the upload trio while the eye is on the
 * download one is exactly the case worth being unambiguous about.
 */
function rateOrderMessage(dir, err) {
	var d = (dir === 'dl') ? _('download') : _('upload');
	switch (err.code) {
		case 'min-gt-base':
			return _('Minimum %s rate (%d) must not exceed the base %s rate (%d).').format(d, err.a, d, err.b);
		case 'max-lt-base':
			return _('Maximum %s rate (%d) must not be below the base %s rate (%d).').format(d, err.a, d, err.b);
		default:
			return _('Minimum %s rate (%d) must not exceed the maximum %s rate (%d).').format(d, err.a, d, err.b);
	}
}

/* --- search/filter -------------------------------------------------------
 * Shows every tab pane at once (via the .cake-filtering class and the injected
 * CSS) and hides option rows whose UCI name or title does not match. Clearing
 * the box restores normal tab behaviour. The matching itself lives in
 * options.optionMatches, which is pure and unit-tested. */
function applyFilter(mapEl, statusEl, query) {
	var q = String(query || '').trim();
	var rows = mapEl.querySelectorAll('.cbi-value[data-name]');
	var shown = 0;

	if (q === '') {
		mapEl.classList.remove('cake-filtering');
		rows.forEach(function (r) { r.style.removeProperty('display'); });
		statusEl.textContent = '';
		return;
	}

	mapEl.classList.add('cake-filtering');
	rows.forEach(function (r) {
		/* A heading groups the rows that follow it. Filtering flattens every
		 * tab into one list and drops most of those rows, so a heading has
		 * nothing left to head -- hide them all rather than caption a result
		 * set they no longer describe. */
		if (r.querySelector('.cake-subhead')) {
			r.style.display = 'none';
			return;
		}
		var name = r.getAttribute('data-name') || '';
		var titleEl = r.querySelector('.cbi-value-title');
		var title = titleEl ? titleEl.textContent : '';
		if (options.optionMatches(q, name, title)) {
			r.style.removeProperty('display');
			shown++;
		}
		else {
			r.style.display = 'none';
		}
	});

	statusEl.textContent = (shown === 0)
		? _('No options match "%s"').format(q)
		: _('%d option field(s) match "%s"').format(shown, q);
}

/* CSS class for a dl_if/ul_if warning level. */
function warnClass(level) {
	if (level === 'warn') return 'alert-message warning';
	if (level === 'info') return 'alert-message';
	if (level === 'ok') return 'cake-if-ok';
	return '';
}

/*
 * Refresh the SQM notice under one section's dl_if/ul_if widget. The value is
 * never rejected, only annotated, so an existing value still shows even when
 * SQM is not configured. The decision itself (live.interfaceStatus) is pure and
 * unit-tested.
 */
function updateIfWarning(opt, section_id, direction, sqm) {
	var el = opt.getUIElement(section_id);
	if (!el || !el.node)
		return;
	var field = el.node.parentNode;
	if (!field)
		return;

	var res = live.interfaceStatus(el.getValue(), sqm, direction);
	var node = field.querySelector('.cake-if-warn');

	if (res.level === 'none') {
		if (node)
			node.remove();
		return;
	}

	if (!node) {
		node = E('div', { 'class': 'cake-if-warn' });
		field.appendChild(node);
	}
	node.className = 'cake-if-warn ' + warnClass(res.level);
	node.setAttribute('data-level', res.level);
	node.setAttribute('data-direction', direction);
	node.textContent = res.message;
}

return view.extend({
	render: function () {
		return callSqmInterfaces().then(L.bind(this.renderForm, this), L.bind(function () {
			/* rpcd unreachable (e.g. package not yet installed): fall back to an
			 * empty, not-present SQM view -- fields stay usable, warnings say so. */
			return this.renderForm({});
		}, this));
	},

	renderForm: function (sqm) {
		var ifChoices = live.interfaceChoices(sqm);

		/* The form must render exactly the 66 upstream options, split across
		 * groups as expected. If it does not, say so rather than let the page
		 * look complete -- that catches both a UI option the daemon has never
		 * heard of and an option quietly dropped from the list. */
		var coverage = options.coverageReport(options.OPTIONS);

		var m = new form.Map('cake-autorate', _('CAKE Autorate'),
			_('Adaptive per-flow bandwidth control for CAKE SQM. Each section below is one independent instance (one WAN). The section name is the instance id and names the daemon config, log file and service.'));

		var s = m.section(form.TypedSection, 'cake-autorate');
		s.anonymous = false;
		s.addremove = true;
		s.addbtntitle = _('Add instance');

		/*
		 * "Add instance" stays a TEXT field with suggestions rather than becoming a
		 * dropdown, for three reasons:
		 *   1. The id must be a UCI section name ([a-zA-Z0-9_]+), but real WAN
		 *      devices are routinely pppoe-wan / eth0.2 / wan.835 -- a dropdown of
		 *      live interfaces would offer names UCI then rejects.
		 *   2. The id is a free-form label naming the daemon config, log file and
		 *      service; a closed list would block legitimate names (starlink,
		 *      backup_lte) and there is no 1:1 interface->instance mapping anyway,
		 *      since an instance carries dl_if AND ul_if as options.
		 *   3. It matches the feed: the apps that override renderSectionAdd
		 *      (mwan3, libreswan, strongswan-swanctl, xfrpc) all AUGMENT the name
		 *      input with validators; none swap it for a select.
		 * So: native <datalist> suggestions derived from the SQM egress devices,
		 * plus a validator that explains the naming rule and catches duplicates.
		 */
		s.renderSectionAdd = function (extra_class) {
			var el = form.TypedSection.prototype.renderSectionAdd.apply(this, arguments);
			var nameEl = el.querySelector('.cbi-section-create-name');
			if (!nameEl)
				return el;

			var suggestions = options.instanceNameSuggestions(ifChoices.ul, this.cfgsections());
			if (suggestions.length) {
				var listId = 'cake-autorate-instance-names';
				el.appendChild(E('datalist', { 'id': listId },
					suggestions.map(function (n) { return E('option', { 'value': n }); })));
				nameEl.setAttribute('list', listId);
				nameEl.setAttribute('placeholder', _('e.g. %s').format(suggestions[0]));
			}
			else {
				nameEl.setAttribute('placeholder', _('e.g. wan'));
			}

			/*
			 * A second validator on the same input. ui.addValidator adds a
			 * listener rather than replacing one, so the built-in validator keeps
			 * enabling the Add button and enforcing the uciname character set,
			 * and this one adds the check it cannot make: a name already in use.
			 * Bad characters are left to 'uciname' -- its assert runs before this
			 * callback, so a message here would never be seen, and users get
			 * LuCI's standard wording as they do everywhere else. Marking the
			 * field invalid is enough to block creation: the Add handler bails on
			 * a field carrying .cbi-input-invalid.
			 */
			var section = this;
			ui.addValidator(nameEl, 'uciname', true, function (v) {
				if (v !== '' && section.cfgsections().indexOf(v) !== -1)
					return _('An instance named "%s" already exists.').format(v);
				return true;
			}, 'blur', 'keyup');

			return el;
		};

		/*
		 * Tab descriptions are STRINGS, never DOM nodes.
		 *
		 * s.tab() is called once for the section type, but renderTabContainers
		 * runs per instance and appends whatever `description` holds into that
		 * instance's pane. A string is re-created each time; a node is one
		 * object, so appending it to the second instance MOVES it out of the
		 * first. Three tabs used to carry a node here -- a description plus a
		 * documentation link -- and on a two-WAN box those three tabs showed no
		 * description at all on every instance but the last.
		 *
		 * The link that made them nodes is gone rather than fixed: it pointed at
		 * the same repository root as the link in the page header, a few lines
		 * above, with no anchor to distinguish it.
		 */
		TABS.forEach(function (t) {
			s.tab(t.id, t.title, t.descr);
		});

		/* The procd gate. Not one of the 66 upstream options and never written
		 * into the daemon config; leads the Essentials tab. */
		var en = s.taboption('essentials', form.Flag, 'enabled', _('Enabled'),
			_('Master switch for this instance. Turn on once the interfaces and rates are correct for your line.') +
			' (<code>enabled</code>)');
		en.rmempty = false;

		/* dl_if / ul_if options, captured so the post-render pass can seed their
		 * warnings for every existing section. */
		var ifOpts = {};
		/* Every generated option, so the shaper-rate trios can be wired up after
		 * the loop (a trio needs all three members to exist first). */
		var rateOpts = {};

		/* One field per upstream option, generated from the metadata, so the
		 * form always matches options.OPTIONS. */
		options.OPTIONS.forEach(function (opt) {
			var o, dt = options.datatypeFor(opt);
			var title = humanize(opt.name);
			var descr = describe(opt);

			/* taboption() renders in call order, so adding the heading here --
			 * before this option's own field -- is what places it. */
			if (SUBHEADINGS[opt.name]) {
				var h = s.taboption(opt.group, SubHeading, '_subhead_' + opt.name, '');
				h.subhead = SUBHEADINGS[opt.name];
			}

			/* The two interface fields become comboboxes offering the SQM-derived
			 * devices. Free text is still accepted, so a value set before SQM
			 * existed keeps showing; a value SQM does not back raises a warning
			 * rather than blocking the save. */
			if (opt.name === 'dl_if' || opt.name === 'ul_if') {
				var direction = (opt.name === 'dl_if') ? 'dl' : 'ul';
				var choices = (direction === 'dl') ? ifChoices.dl : ifChoices.ul;
				o = s.taboption(opt.group, form.Value, opt.name, title, descr);
				choices.forEach(function (c) { o.value(c, c); });
				o.rmempty = true;
				o.onchange = function (ev, section_id) {
					updateIfWarning(this, section_id, direction, sqm);
				};
				ifOpts[opt.name] = { opt: o, direction: direction };
				return;
			}

			if (opt.type === 'bool') {
				o = s.taboption(opt.group, form.Flag, opt.name, title, descr);
				/* A checkbox has no "unset" state to show, so an omitted bool
				 * has to mean something, and for the daemon it means "use my
				 * built-in value" -- which for adjust_dl_shaper_rate, debug,
				 * enable_sleep_function and friends is 1. LuCI's Flag drops an
				 * option whenever it equals o.default and rmempty is on, so
				 * with the stock default of '0' unchecking one of those boxes
				 * deleted the option and the daemon silently kept the feature
				 * ON while the form showed it off. Pin the packaged default so
				 * a fresh instance renders correctly, and keep rmempty off so
				 * the saved config always states 0 or 1 outright. */
				o.default = opt.def ? '1' : '0';
			}
			else if (opt.type === 'list') {
				o = s.taboption(opt.group, form.DynamicList, opt.name, title, descr);
				o.datatype = 'ipaddr';
			}
			else if (opt.type === 'string' && opt.choices) {
				o = s.taboption(opt.group, form.ListValue, opt.name, title, descr);
				opt.choices.forEach(function (c) { o.value(c, c); });
			}
			else {
				o = s.taboption(opt.group, form.Value, opt.name, title, descr);
				if (dt)
					o.datatype = dt;
			}

			/* String options whose upstream default is empty may be blanked;
			 * everything else keeps its packaged/upstream default when omitted.
			 * Bools opt out: an omitted bool would be read as the daemon's own
			 * default, which is the opposite of what an unchecked box means. */
			o.rmempty = (opt.type !== 'bool');
			rateOpts[opt.name] = o;
		});

		/* Enforce the min <= base <= max ordering the Essentials help promises.
		 * A datatype only sees its own field, so without this the form happily
		 * saved min > base and handed the daemon a nonsensical config. Attached
		 * to all six fields so the error appears on whichever one the user is
		 * editing; returning a string makes LuCI show it under the field and
		 * refuse the save. */
		options.RATE_TRIOS.forEach(function (trio) {
			var members = [trio.min, trio.base, trio.max];

			members.forEach(function (name) {
				var o = rateOpts[name];
				if (!o)
					return;

				o.validate = function (section_id, value) {
					var self = this;
					function other(n) {
						/* Take the field being edited from `value`; read the
						 * other two off their widgets. */
						if (n === name)
							return value;
						var found = self.map.lookupOption(n, section_id);
						return (found && found[0]) ? found[0].formvalue(section_id) : null;
					}
					var err = options.checkRateOrder(other(trio.min), other(trio.base), other(trio.max));
					return err ? rateOrderMessage(trio.dir, err) : true;
				};

				/* Re-validate the siblings too: fixing `base` must clear a stale
				 * error still shown on `min`, which only re-checks itself. */
				o.onchange = function (ev, section_id) {
					members.forEach(function (n) {
						if (n === name)
							return;
						var found = this.map.lookupOption(n, section_id);
						if (found && found[0])
							found[0].triggerValidation(section_id);
					}, this);
				};
			});
		});

		return m.render().then(function (mapEl) {
			var nodes = [];

			/* CSS: while filtering, reveal every tab pane and hide the tab bar
			 * so cross-group matches are visible. */
			nodes.push(E('style', { 'type': 'text/css' },
				'.cake-filtering [data-tab-title]{height:auto !important;opacity:1 !important;overflow:visible !important;}' +
				'.cake-filtering .cbi-tabmenu{display:none !important;}' +
				'.cake-filtering .cbi-tab-descr{display:none !important;}' +
				'#cake-autorate-toolbar{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;margin:.5em 0;}' +
				'#cake-autorate-filter{flex:1 1 20em;max-width:32em;}' +
				'#cake-autorate-filter-status{opacity:.75;font-size:90%;}' +
				/* The UCI key describe() appends. The stock themes leave <code>
				 * inside a description at body size and body colour, where it
				 * competes with the sentence it is annotating; this makes it read
				 * as a key -- monospace, slightly smaller, slightly muted --
				 * without inventing a colour the theme does not have. */
				'.cbi-value-description code{font-family:monospace;font-size:92%;opacity:.8;}' +
				'.cake-if-warn{margin-top:.4em;padding:.4em .6em;font-size:90%;}' +
				'.cake-if-warn.cake-if-ok{color:#2e7d32;padding:.2em 0;}' +
				/* flex-basis 100%: a .cbi-value row is a flex container in the
				 * stock themes, and without it the heading shares the line with
				 * the (empty) label column instead of spanning the row. */
				'.cake-subhead{flex:1 1 100%;width:100%;display:block;' +
				'margin:1.2em 0 .2em;padding-bottom:.2em;font-size:1.05em;' +
				'border-bottom:1px solid rgba(128,128,128,.35);}'));

			nodes.push(E('p', {}, [
				E('strong', {}, 'cake-autorate ' + UPSTREAM_VERSION), ' · ',
				E('a', { 'href': DOC_URL, 'target': '_blank', 'rel': 'noreferrer' }, DOC_TITLE)
			]));

			/* The one thing this page cannot say field by field: SQM is missing
			 * altogether, so there is no qdisc for any instance to adjust.
			 *
			 * Its counterpart -- naming the egress/ingress choices when SQM IS
			 * configured -- used to sit here too and is gone: the interface
			 * fields already offer exactly those devices in their dropdowns and
			 * annotate the chosen one underneath, so restating the same two
			 * lists at the top of the page was a third copy of an answer the
			 * user is looking straight at. */
			if (!(sqm && sqm.sqm_config_present)) {
				nodes.push(E('p', { 'id': 'cake-autorate-sqm-note', 'class': 'cbi-value-description' },
					_('SQM is not configured yet, so the interface fields cannot be validated against a live CAKE qdisc. Configure SQM first; the fields still accept a value.')));
			}

			if (!coverage.ok) {
				nodes.push(E('div', { 'class': 'alert-message error' }, [
					E('strong', {}, _('Configuration form coverage check FAILED.')), ' ',
					_('The form no longer renders exactly the 66 supported options: %s')
						.format(coverage.errors.join('; '))
				]));
			}

			/* Search / filter toolbar. */
			var statusEl = E('span', { 'id': 'cake-autorate-filter-status' }, '');
			var inputEl = E('input', {
				'id': 'cake-autorate-filter',
				'type': 'search',
				'class': 'cbi-input-text',
				/* Mentions UCI names on purpose: with the keys no longer printed
				 * on each row, this is how someone reading the upstream docs
				 * finds the field for a config key. */
				'placeholder': _('Search titles and UCI option names, e.g. "shaper" or "owd_delta"…'),
				'autocomplete': 'off',
				'keyup': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); },
				'search': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); }
			});
			nodes.push(E('div', { 'id': 'cake-autorate-toolbar' }, [
				E('label', { 'for': 'cake-autorate-filter' }, _('Search options') + ':'),
				inputEl, statusEl
			]));

			nodes.push(mapEl);

			/* Seed the dl_if/ul_if warnings for every existing section (onchange
			 * only fires on edit). getUIElement no-ops safely if a widget is not
			 * yet in the DOM. */
			var sids = s.cfgsections();
			Object.keys(ifOpts).forEach(function (name) {
				var entry = ifOpts[name];
				sids.forEach(function (sid) {
					updateIfWarning(entry.opt, sid, entry.direction, sqm);
				});
			});

			return E('div', {}, nodes);
		});
	}
});
