'use strict';
'require view';
'require form';
'require ui';
'require cake-autorate.options as options';

/*
 * cake-autorate configuration form (task 7).
 *
 * A form.Map over the `cake-autorate` UCI type with a named, add/removable
 * TypedSection, so multiple instances can be created / edited / enabled /
 * deleted. Fields are grouped into tabs led by Essentials, with a client-side
 * search that filters across every group. EVERY field except the package-local
 * `enabled` procd gate is generated by iterating options.OPTIONS -- the 66
 * upstream options -- so the rendered set cannot drift from the daemon's.
 *
 * The live status view and the SQM-validated interface pickers are task 9; this
 * file is config editing only. Version shown is the PACKAGE version (3.2.2), not
 * the daemon's stale self-reported 3.2.1 (upstream cosmetic bug at tag v3.2.2).
 *
 * Stable selectors for tasks 11/12 (Playwright):
 *   - each option row:      div.cbi-value[data-name="<uci_option>"]
 *   - the section:          UCI type "cake-autorate", named (anonymous=false)
 *   - the search box:       input#cake-autorate-filter
 *   - the group tabs:       [data-tab="essentials|shaper|pingers|reflectors|
 *                            detection|idle|logging"]
 */

var PKG_VERSION = '3.2.2';
var DOC_URL = 'https://github.com/lynxthecat/cake-autorate/wiki';

var TABS = [
	{ id: 'essentials', title: _('Essentials'),
	  descr: _('The minimum a fresh instance needs: the two interfaces and the min/base/max shaper rates for each direction. Everything else has a working default.') },
	{ id: 'shaper', title: _('Shaper rates & response'),
	  descr: _('How aggressively the shaper rate is moved up and down in response to load and bufferbloat.'), doc: true },
	{ id: 'pingers', title: _('Pingers'),
	  descr: _('Which probe binary is used and how many reflectors are pinged how often.') },
	{ id: 'reflectors', title: _('Reflectors'),
	  descr: _('The pool of ICMP targets and how misbehaving ones are detected and rotated out.'), doc: true },
	{ id: 'detection', title: _('Delay & bufferbloat detection'),
	  descr: _('One-way-delay thresholds and the EWMA smoothing that decide when the link is bufferbloated.'), doc: true },
	{ id: 'idle', title: _('Idle, sleep & stalls'),
	  descr: _('When the connection counts as idle or stalled and how the pingers sleep to save CPU.') },
	{ id: 'logging', title: _('Logging & output'),
	  descr: _('Which log streams the daemon emits. Options marked package-managed are overridden by the service so the status view and collectd always have data.') }
];

var ACRONYMS = {
	dl: 'DL', ul: 'UL', owd: 'OWD', ewma: 'EWMA', kbps: 'Kbit/s',
	ms: 'ms', kb: 'KB', thr: 'threshold', avg: 'avg', mins: 'min',
	'if': 'interface', args: 'args'
};

function humanize(name) {
	return name.split('_').map(function (w) {
		return ACRONYMS[w.toLowerCase()] || (w.charAt(0).toUpperCase() + w.slice(1));
	}).join(' ');
}

function describe(opt) {
	var d = opt.desc;
	if (opt.units)
		d += '  —  ' + opt.units;
	return d + '  ·  ' + _('UCI key') + ': ' + opt.name;
}

/* A tab description node with an optional upstream documentation link. */
function tabDescr(tab) {
	if (!tab.doc)
		return tab.descr;
	return E('span', {}, [
		tab.descr, ' ',
		E('a', { 'href': DOC_URL, 'target': '_blank', 'rel': 'noreferrer' }, _('Upstream documentation →'))
	]);
}

/* --- search/filter -------------------------------------------------------
 * Reveals all tab panes (via the .cake-filtering class + injected CSS) and
 * hides option rows whose UCI name / title do not match the query. Clearing
 * the box restores normal tab behaviour. The match predicate itself
 * (options.optionMatches) is pure and unit-tested. */
function applyFilter(mapEl, statusEl, query) {
	var q = String(query || '').trim();
	var rows = mapEl.querySelectorAll('.cbi-value[data-name]');
	var shown = 0;

	if (q === '') {
		mapEl.classList.remove('cake-filtering');
		rows.forEach(function (r) { r.style.removeProperty('display'); });
		statusEl.textContent = '';
		return;
	}

	mapEl.classList.add('cake-filtering');
	rows.forEach(function (r) {
		var name = r.getAttribute('data-name') || '';
		var titleEl = r.querySelector('.cbi-value-title');
		var title = titleEl ? titleEl.textContent : '';
		if (options.optionMatches(q, name, title)) {
			r.style.removeProperty('display');
			shown++;
		}
		else {
			r.style.display = 'none';
		}
	});

	statusEl.textContent = (shown === 0)
		? _('No options match "%s"').format(q)
		: _('%d option field(s) match "%s"').format(shown, q);
}

return view.extend({
	render: function () {
		/* Load-time coverage guard: the rendered option set MUST be exactly the
		 * 66 upstream options in the expected per-group split, or we refuse to
		 * pretend the form is complete. Prevents the audited "UI option with no
		 * daemon backing" (or a silently dropped option) from recurring. */
		var coverage = options.coverageReport(options.OPTIONS);

		var m = new form.Map('cake-autorate', _('CAKE Autorate'),
			_('Adaptive per-flow bandwidth control for CAKE SQM. Each section below is one independent instance (one WAN). The section name is the instance id and names the daemon config, log file and service.'));

		var s = m.section(form.TypedSection, 'cake-autorate');
		s.anonymous = false;
		s.addremove = true;
		s.addbtntitle = _('Add instance');

		TABS.forEach(function (t) {
			s.tab(t.id, t.title, tabDescr(t));
		});

		/* Package-local procd gate -- NOT one of the 66 upstream options and
		 * never written into the daemon config; leads the Essentials tab. */
		var en = s.taboption('essentials', form.Flag, 'enabled', _('Enabled'),
			_('Master switch for this instance (procd). Turn on once the interfaces and rates are correct for your line.') + '  ·  ' + _('UCI key') + ': enabled');
		en.rmempty = false;

		/* Generate one field per upstream option by iterating the metadata, so
		 * "rendered fields" == options.OPTIONS by construction. */
		options.OPTIONS.forEach(function (opt) {
			var o, dt = options.datatypeFor(opt);
			var title = humanize(opt.name);
			var descr = describe(opt);

			if (opt.type === 'bool') {
				o = s.taboption(opt.group, form.Flag, opt.name, title, descr);
			}
			else if (opt.type === 'list') {
				o = s.taboption(opt.group, form.DynamicList, opt.name, title, descr);
				o.datatype = 'ipaddr';
			}
			else if (opt.type === 'string' && opt.choices) {
				o = s.taboption(opt.group, form.ListValue, opt.name, title, descr);
				opt.choices.forEach(function (c) { o.value(c, c); });
			}
			else {
				o = s.taboption(opt.group, form.Value, opt.name, title, descr);
				if (dt)
					o.datatype = dt;
			}

			/* String options whose upstream default is empty may be blanked;
			 * everything else keeps its packaged/upstream default when omitted. */
			o.rmempty = true;
		});

		return m.render().then(function (mapEl) {
			var nodes = [];

			/* CSS: while filtering, reveal every tab pane and hide the tab bar
			 * so cross-group matches are visible. */
			nodes.push(E('style', { 'type': 'text/css' },
				'.cake-filtering [data-tab-title]{height:auto !important;opacity:1 !important;overflow:visible !important;}' +
				'.cake-filtering .cbi-tabmenu{display:none !important;}' +
				'.cake-filtering .cbi-tab-descr{display:none !important;}' +
				'#cake-autorate-toolbar{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;margin:.5em 0;}' +
				'#cake-autorate-filter{flex:1 1 20em;max-width:32em;}' +
				'#cake-autorate-filter-status{opacity:.75;font-size:90%;}'));

			nodes.push(E('p', {}, [
				E('strong', {}, 'cake-autorate ' + PKG_VERSION), ' · ',
				E('a', { 'href': DOC_URL, 'target': '_blank', 'rel': 'noreferrer' }, _('Upstream documentation'))
			]));

			if (!coverage.ok) {
				nodes.push(E('div', { 'class': 'alert-message error' }, [
					E('strong', {}, _('Configuration form coverage check FAILED.')), ' ',
					_('The form no longer renders exactly the 66 supported options: %s')
						.format(coverage.errors.join('; '))
				]));
			}

			/* Search / filter toolbar. */
			var statusEl = E('span', { 'id': 'cake-autorate-filter-status' }, '');
			var inputEl = E('input', {
				'id': 'cake-autorate-filter',
				'type': 'search',
				'class': 'cbi-input-text',
				'placeholder': _('Filter options by name, e.g. "shaper" or "reflector"…'),
				'autocomplete': 'off',
				'keyup': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); },
				'search': function (ev) { applyFilter(mapEl, statusEl, ev.target.value); }
			});
			nodes.push(E('div', { 'id': 'cake-autorate-toolbar' }, [
				E('label', { 'for': 'cake-autorate-filter' }, _('Search options') + ':'),
				inputEl, statusEl
			]));

			nodes.push(mapEl);
			return E('div', {}, nodes);
		});
	}
});
